[project]
name = "auth0-management"
version = "0.1.0"
description = "Export Auth0 users and their organization data to Excel"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "requests",
    "pandas",
    "openpyxl",
    "auth0-python",
]
